name: DSML
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310hd5e7861_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alembic=1.18.1=pyhcf101f3_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - applaunchservices=0.3.0=pyh534df25_4
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310hfe3a0ae_2
  - arrow=1.4.0=pyhcf101f3_0
  - astroid=4.0.3=py310hbe9552e_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.1.0=pyhcf101f3_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=1.6.0=pyhd8ed1ab_1
  - aws-c-auth=0.8.6=h660070d_4
  - aws-c-cal=0.8.7=h8f38403_0
  - aws-c-common=0.12.0=h5505292_0
  - aws-c-compression=0.3.1=hd84a0f8_2
  - aws-c-event-stream=0.5.4=h3c33643_2
  - aws-c-http=0.9.4=hedcc1e3_4
  - aws-c-io=0.17.0=ha705ebb_6
  - aws-c-mqtt=0.12.2=h82c6c6a_2
  - aws-c-s3=0.7.13=hb857f95_2
  - aws-c-sdkutils=0.2.3=hd84a0f8_2
  - aws-checksums=0.2.3=hd84a0f8_2
  - aws-crt-cpp=0.31.0=h7378f02_4
  - aws-sdk-cpp=1.11.510=hf067f9e_3
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - backports.zstd=1.3.0=py310h2d60bed_0
  - bcrypt=5.0.0=py310hf3301a5_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=26.1.0=pyha5154f8_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.2.0=py310h5b255a4_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310hf5b66c1_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - cryptography=46.0.3=py310h58759cc_1
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - databricks-sdk=0.73.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.19=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.1=pyhcf101f3_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastapi=0.128.0=h0ea4129_1
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.0=pyhcf101f3_1
  - filelock=3.20.3=pyhd8ed1ab_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.2=pyhcf101f3_0
  - flatbuffers=24.12.23=h28594ff_0
  - fonttools=4.61.1=py310hf4fd40f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.7.0=py310ha18c8e3_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gast=0.7.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glib=2.86.3=h7ee6e74_0
  - glib-tools=2.86.3=hb9d6e3a_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h1b1a8f9_2
  - google-auth=2.47.0=pyhcf101f3_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphql-core=3.2.7=pyhcf101f3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.3.0=py310hc7786af_0
  - grpcio=1.67.1=py310h92b281b_2
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - gunicorn=23.0.0=py310hbe9552e_3
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310hc571fcd_101
  - hdf5=1.14.6=nompi_ha698983_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310hfe3a0ae_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huey=2.6.0=pyhcf101f3_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - invoke=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=7.33.0=py310hbe9552e_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=7.0.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.1.0=pyhcf101f3_0
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jellyfish=1.2.1=py310h53169e7_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kaldi=5.5.1112=cpu_h085be33_9
  - keras=3.12.0=pyh753f3f9_0
  - keyring=25.7.0=pyh534df25_0
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libarrow=19.0.1=h9828ad4_3_cpu
  - libarrow-acero=19.0.1=hf07054f_3_cpu
  - libarrow-dataset=19.0.1=hf07054f_3_cpu
  - libarrow-substrait=19.0.1=h4239455_3_cpu
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp18.1=18.1.8=default_h73dfc95_17
  - libclang13=21.1.0=default_h6e8f826_1
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.86.3=hfe11c1f_0
  - libgoogle-cloud=2.36.0=hdbe95d5_0
  - libgoogle-cloud-storage=2.36.0=h7081f7f_0
  - libgrpc=1.67.1=h0a426d6_2
  - libheif=1.19.7=gpl_h79e6334_100
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblapacke=3.11.0=5_h1b118fd_openblas
  - libllvm18=18.1.8=default_h3f49643_9
  - libllvm21=21.1.0=h846d351_0
  - liblzma=5.8.2=h8088a28_0
  - libml_dtypes-headers=0.5.4=h707e725_0
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_hf332438_0
  - libopentelemetry-cpp=1.18.0=h0c05b2d_1
  - libopentelemetry-cpp-headers=1.18.0=hce30654_1
  - libopus=1.6.1=h1a92334_0
  - libparquet=19.0.1=h636d7b7_3_cpu
  - libpng=1.6.54=h132b30e_0
  - libpq=18.1=h944245b_2
  - libprotobuf=5.28.3=h3bd63a1_1
  - libre2-11=2024.07.02=h07bc746_2
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.1.0=h57eeb1c_0
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h1590b86_0
  - libtensorflow_cc=2.18.0=cpu_hf321e49_1
  - libtensorflow_framework=2.18.0=cpu_h2398287_1
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.6.0=cpu_generic_hb0d28ef_1
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - mako=1.3.10=pyhcf101f3_1
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib=3.10.8=py310hb6292c7_0
  - matplotlib-base=3.10.8=py310h0181960_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - ml_dtypes=0.4.0=py310hfd37619_2
  - mlflow=3.8.1=pyh707e725_0
  - mlflow-skinny=3.8.1=pyh707e725_0
  - mlflow-ui=3.8.1=pyh707e725_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py310hdf731dd_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - namex=0.1.0=pyhd8ed1ab_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.16.6=hc388f54_1
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbconvert-pandoc=7.16.6=h7d6f222_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h784d473_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.5.2=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.38=heaf21c2_0
  - nss=3.118=h1c710a3_0
  - numpy=2.2.6=py310h4d83441_0
  - numpydoc=1.10.0=pyhcf101f3_0
  - openfst=1.8.3=h950e60b_3
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.39.1=pyhd8ed1ab_0
  - opentelemetry-proto=1.39.1=pyhd8ed1ab_0
  - opentelemetry-sdk=1.39.1=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.60b1=pyhd8ed1ab_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.18.0=py310h0e897d2_0
  - orc=2.1.1=h74f7c94_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pandoc=3.8.3=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=1.0.3=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310hc037f36_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310hc74094e_0
  - protobuf=5.28.3=py310h853098b_0
  - psutil=7.2.1=py310haea493c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pyarrow=19.0.1=py310hb6292c7_1
  - pyarrow-core=19.0.1=py310h92b138f_1_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hf3301a5_1
  - pydantic-extra-types=2.11.0=pyhd8ed1ab_0
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.2=py310h72544b6_0
  - pyobjc-core=12.1=py310h9d23ab5_0
  - pyobjc-framework-cocoa=12.1=py310h8579ff5_0
  - pyobjc-framework-coreservices=12.1=py310hfe3a0ae_2
  - pyobjc-framework-fsevents=12.1=py310hbe9552e_2
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py310hc3ce690_2
  - pyqt5-sip=12.17.0=py310hc7786af_2
  - pyqtwebengine=5.15.11=py310hd99ea14_0
  - pysocks=1.7.1=pyha55dd90_7
  - pyspark=4.1.1=pyhd8ed1ab_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=1.1.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.3.3=pyhd8ed1ab_0
  - python-multipart=0.0.21=pyhcf101f3_1
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python.app=1.4=py310h1231ce0_5
  - python_abi=3.10=8_cp310
  - pytokens=0.3.0=pyhcf101f3_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytorch=2.6.0=cpu_generic_py310_h3625fd7_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - qdarkstyle=3.0.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=h9b65787_6
  - qt-webengine=5.15.9=h2903aaf_7
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.2.2=pyhd8ed1ab_1
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.4.3=pyhd8ed1ab_1
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - rav1e=0.7.1=h0716509_3
  - re2=2024.07.02=h6589ca4_2
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py310hf3301a5_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - rtree=1.4.1=pyh11ca60a_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=80.10.1=pyh332efcf_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sip=6.12.0=py310h8740e61_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=5.2.2=py310hca03da5_1
  - spyder-kernels=2.2.1=py310hbe9552e_1
  - sqlalchemy=2.0.45=py310hfe3a0ae_0
  - sqlparse=0.5.5=pyhcf101f3_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - statsmodels=0.14.6=py310hfdc7867_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py310h0cf7f6c_4
  - tensorflow=2.18.0=cpu_py310hd689282_1
  - tensorflow-base=2.18.0=cpu_py310ha6cf98d_1
  - tensorflow-estimator=2.18.0=cpu_py310h0e61965_1
  - termcolor=3.3.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyhc90fa1f_1
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tomlkit=0.14.0=pyha770c72_0
  - torchaudio=2.7.0=cpu_py310h1acedd7_0
  - torchvision=0.21.0=cpu_py310_hc307cfc_1
  - torchvision-extra-decoders=0.0.2=py310ha3957cf_2
  - tornado=6.5.4=py310hfe3a0ae_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - ujson=5.11.0=py310hf6ed2a0_1
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyhc90fa1f_0
  - uvicorn-standard=0.40.0=h4cd5af1_0
  - uvloop=0.22.1=py310hfe3a0ae_1
  - watchdog=6.0.0=py310hfe3a0ae_2
  - watchfiles=1.1.1=py310h53169e7_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=16.0=py310haea493c_1
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.1=py310hfe3a0ae_1
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=py310hf4fd40f_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - multiprocess==0.70.19
      - salib==1.5.2
      - tqdm==4.67.2
